### ISSUE TITLE
Cannot find the Options List

### ISSUE THREAD

**Issue by Losto88** [TimeShining/Android-Dev-Tools#1]
If i use the Buttons to switch the Developer's Options, its only open the overview, if i go back in the App, it says "Cannot find the Options List."
![Screenshot_20200217-215113_Dev Tools](https://user-images.githubusercontent.com/60311319/74807129-fdf77f00-52e7-11ea-9b18-bece50e07c50.jpg)

**Comment by Trinea** [comment]
Can you tell me which button do you have clicked? and what's your phone model and Android  version?

**Comment by Losto88** [comment]
Model: SM-G975F
Manufacturer: samsung
Board: exynos9820
Device: beyond2
Product: beyond2lteeea
CPU Cores: 8
CPU Bit: 64-Bit
Memory: Total 7.23 GB, Avail 3.0 GB
Storage: Total 109.93 GB, Avail 76.83 GB
Resolution: 1080 * 2280 px / 420 dp
Screen Size: 2.7" * 5.8" / 6.4 Inches

Android 10 / API 29
Baseband Version: G975FXXS3BSL4,G975FXXS3BSL4
Build Number: QP1A.190711.020.G975FXXS3BSL4
Linux Kernel Version: 4.14.113-17369399
Http User Agent: Dalvik/2.1.0 (Linux; U; Android 10; SM-G975F Build/QP1A.190711.020)




Thank you!



On Thu, Feb 20, 2020 at 5:45 PM +0100, "Trinea" <notifications@github.com> wrote:












Can you tell me which button do you have clicked? and what's your phone model and Android  version?

**Comment by Trinea** [comment]
I'm Sorry I don't have a Samsung phone, I will test it when I have it

**Comment by Losto88** [comment]
How can i help you?

**Comment by hIUG** [comment]
Having the same issue on a Samsung device when clicking the `Stay awake` tool.
Model: SM-G975U
Manufacturer: samsung
Board: msmnile
Device: beyond2q
Product: beyond2qltesq
CPU Cores: 8
CPU Bit: 64-Bit
CPU Model: Qualcomm Technologies, Inc SM8150
Memory: Total 7.29 GB, Avail 1.58 GB
Storage: Total 463.67 GB, Avail 366.35 GB
Resolution: 1440 * 3040 px / 560 dp
Screen Size: 2.8" * 5.8" / 6.4 Inches

**Comment by quocbao38** [comment]
> If i use the Buttons to switch the Developer's Options, its only open the overview, if i go back in the App, it says "Cannot find the Options List."
> ![Screenshot_20200217-215113_Dev Tools](https://user-images.githubusercontent.com/60311319/74807129-fdf77f00-52e7-11ea-9b18-bece50e07c50.jpg)

Thank you

**Comment by Rayhanss** [comment]
Hello dev tools team i very much happy bcoz of such fantastic service but that hacker is again customing apps from apps Store so can help for application custom pull link code and my personal data is i want hackers had paid money to from account only

**Comment by TQuocBao86** [comment]
Model: SM-G975F Manufacturer: samsung Board: exynos9820 Device: beyond2 Product: beyond2lteeea CPU Cores: 8 CPU Bit: 64-Bit Memory: Total 7.23 GB, Avail 3.0 GB Storage: Total 109.93 GB, Avail 76.83 GB Resolution: 1080 * 2280 px / 420 dp Screen Size: 2.7" * 5.8" / 6.4 Inches Android 10 / API 29 Baseband Version: G975FXXS3BSL4,G975FXXS3BSL4 Build Number: QP1A.190711.020.G975FXXS3BSL4 Linux Kernel Version: 4.14.113-17369399 Http User Agent: Dalvik/2.1.0 (Linux; U; Android 10; SM-G975F Build/QP1A.190711.020) Thank you! On Thu, Feb 20, 2020 at 5:45 PM +0100, "Trinea" <notifications@github.com> wrote: Can you tell me which button do you have clicked? and what's your phone model and Android version? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
